apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    uid: docker-tempo-datasource
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'docker-loki-datasource'
        tags: []
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'docker-prometheus-datasource'
        spanStartTimeShift: '-2m'
        spanEndTimeShift: '2m'
      search:
        hide: false
      streamingEnabled:
        search: false
        metrics: false
