modLoader = "kotlinforforge"
loaderVersion = "[5,)"
issueTrackerURL = "https://github.com/MC-Telemetry/mc-telemetry-core/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
logoFile = "assets/mcotelcore/icon.png"
displayName = "MC Telemetry Core"
authors = "pixix4, ZincFox"
description = '''
Monitor Minecraft with OpenTelemetry'''

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mcotelcore.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "owo"
mandatory = true
versionRange = "[${owo_neoforge_version},)"
ordering = "AFTER"
side = "BOTH"
